### ISSUE TITLE
bug: Add support for rack elevations API call

### ISSUE THREAD

**Issue by pobradovic08** [netbox-community/netbox-python#12]
# Bug Report

**Current behavior:**

There is no way to call `/api/dcim/racks/{id}/elevation/` API endpoint.
Similar situation to Available resources in IPAM (#8)

**Comment by pobradovic08** [comment]
I currently have it implemented like this: https://github.com/netbox-community/netbox-python/commit/4cc359ffe21e9394f5d26bdac3bc1005ac2b0887

Example call would be `nb.dcim.racks.elevation.all(id=rack_id)` (inline with option 1 in #10).

Also I'm unsure that `ElevationAPIResource` class should be named like this. Maybe it should have a more generic name as there is nothing specific to Rack Elevations and it could be used for other API endponts that provide additional information about some entity?

**Comment by arthanson** [comment]
@pobradovic08 can you open up a PR here?

**Comment by arthanson** [comment]
Fixed via #15
